В данной лабораторной работе:

- была выполнена реализация функции two_sum(data);

- в ходе работы были прописаны все возможные ошибки; 

пример:

    if type(nums) != type([]): # прописываем ошибки
        raise ValueError('Ошибка! Неверный тип данных.')

- также были прописаны тесты для нашей функции, в которых производился контроль ошибок и проверялась штатная работа фуекции
тесты выполнялись припомощи библиотеки unittest

пример:

    def test_twos_innums(self):
        '''тест вывода ошибки : неверный тип данных в nums'''
        with self.assertRaises(ValueError):
            two_sum([1, 2, 3, '4'], 5)
            
    def test_twos_simple(self):
        '''проверка штатной работы'''
        self.assertEqual(two_sum([3, 3], 6), [0, 1])
